function a1() { $(".a1").animate({left:'0'})}
function a2() { $(".a2").animate({left:'0'})}
function b1() { $(".b1").animate({left:'0'})}
function b2() { $(".b2").animate({left:'0'})}
function b3() { $(".b3").animate({left:'0'})}
function b4() { $(".b4").animate({left:'0'})}
function c1() { $(".c1").animate({left:'0'})}
function c2() { $(".c2").animate({left:'0'})}
function c3() { $(".c3").animate({left:'0'})}
function c4() { $(".c4").animate({left:'0'})}
function c5() { $(".c5").animate({left:'0'})}
function c6() { $(".c6").animate({left:'0'})}
function c7() { $(".c7").animate({left:'0'})}
function c8() { $(".c8").animate({left:'0'})}